### ISSUE TITLE
TREE.ID.YR - needs to be a required column?

### ISSUE THREAD

**Issue by jess-shue** [seanmcm/RDendrom#5]
Attempting to run code for TEMPEST dendrometer data. I'm following the Using RDendrom vignette and on the second block of code using 'get.optimized.dendro' function R is giving me  "Error in unique(TREE.ID.YR) : object 'TREE.ID.YR' not found".

This is not listed as a required column, should it be added to the dataset initially or is supposed to be generated by the code somewhere else? Attempted to add a column with that name by copying the code for TREE.SITE.ID from DENDRO_BASE_FUNCTIONS.R but same error was returned:
TMP$TREE.ID.YR <- paste(as.character(TMP$TREE_ID),
                        as.character(TMP$YEAR), sep = "_")

**Comment by seanmcm** [comment]
I think it’s added upstream. In some processing code. Or in the function that might have failed. In the code there is a place where we paste Tree.id and Year to make a unique id. That’s where this is failing.

If you can, load all the necessary variables from the arguments section of the function (i.e., if there is a dff for the data, then make dff <- whatever data.frame the data are in … etc. so that you can run the function code line by line and see where it fails, and when it does, what values all the variables have.

I can do this with you if you don’t get this drivel.

Thanks for starting this!

**Comment by jess-shue** [comment]
Could we go through it together sometime? I tend to get confused between the functions portion of the code and where/what I should be looking at!

**Comment by seanmcm** [comment]
absolutely. Can we dip in tomorrow around 9?  I’m going to get a booster before, but should be back. I do have aa 4PM interview, but let’s do a quick check.
